[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/kubernetes"

[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/apiserver"

[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/apimachinery"

# Fix vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[prune]
  go-tests = true
  unused-packages = true
