---
kind: Service
apiVersion: v1
metadata:
  name: busybox-udp-service
spec:
  selector:
    app: busybox-udp
  type: LoadBalancer
  ports:
  - name: busybox-udp-port
    port: 5300
    targetPort: 5300
    protocol: UDP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: busybox-udp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-udp
    spec:
      containers:
      - name: busybox
        image: busybox
        ports:
        - containerPort: 5300
        command:
        - /bin/sh
        - -c
        - |
          nc -ulp 5300